os: linux
dist: jammy

jobs:
  include:
    - name: "job one"
      vm:
        create:
          name:  imag_11
      script:
        - echo "condition with job oneeee"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 50
